# -*- coding: utf-8 -*-
"""topsis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VigoKOs1PlgFDo7ObkCRqD-Y9asYVEjm
"""

import sys
import pandas as pd
import numpy as np
import os

def error(msg):
    print(f"Error: {msg}")
    sys.exit(1)

if len(sys.argv) != 5:
    error("Usage: python topsis.py <InputDataFile> <Weights> <Impacts> <OutputResultFileName>")

input_file = sys.argv[1]
weights_str = sys.argv[2]
impacts_str = sys.argv[3]
output_file = sys.argv[4]

if not os.path.isfile(input_file):
    error("Input file not found")

try:
    df = pd.read_csv(input_file)
except:
    error("Unable to read the input file")

if df.shape[1] < 3:
    error("Input file must contain three or more columns")

criteria_data = df.iloc[:, 1:]

if not np.all(criteria_data.applymap(lambda x: isinstance(x, (int, float)))):
    error("Columns from 2nd to last must contain numeric values only")

weights = weights_str.split(",")
impacts = impacts_str.split(",")

if len(weights) != criteria_data.shape[1]:
    error("Number of weights must match number of criteria columns")

if len(impacts) != criteria_data.shape[1]:
    error("Number of impacts must match number of criteria columns")

try:
    weights = np.array(weights, dtype=float)
except:
    error("Weights must be numeric values")

for imp in impacts:
    if imp not in ['+', '-']:
        error("Impacts must be either '+' or '-'")

norm = np.sqrt((criteria_data ** 2).sum())
normalized = criteria_data / norm
weighted = normalized * weights

ideal_best = []
ideal_worst = []

for i in range(len(impacts)):
    if impacts[i] == '+':
        ideal_best.append(weighted.iloc[:, i].max())
        ideal_worst.append(weighted.iloc[:, i].min())
    else:
        ideal_best.append(weighted.iloc[:, i].min())
        ideal_worst.append(weighted.iloc[:, i].max())

ideal_best = np.array(ideal_best)
ideal_worst = np.array(ideal_worst)

distance_best = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
distance_worst = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

topsis_score = distance_worst / (distance_best + distance_worst)
rank = topsis_score.rank(ascending=False).astype(int)

df['Topsis Score'] = topsis_score
df['Rank'] = rank

df.to_csv(output_file, index=False)

print("TOPSIS analysis completed successfully.")